// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'phone': string;
  'phoneNumbers': string;
}
export const cssExports: CssExports;
export default cssExports;
